version: "3.4"

name: "retromachina-monorepo"

services:
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    container_name: retro-backup
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET_NAME=backupy-newbies
      - AWS_S3_PATH=retromachina
      - BACKUP_RETENTION_DAYS=14
    volumes:
      - retro-db:/backup/retromachina:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  retro-db:
    image: mariadb:10.7
    restart: unless-stopped
    container_name: retro-db
    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - retro-db:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_ROOT_PASSWORD: retro
      MYSQL_DATABASE: retro
    ports:
      - "3306:3306"
    networks:
      - retro-back-local
  retro-web:
    image: ghcr.io/newbies-workplace/retromachina-web:latest
    restart: unless-stopped
    environment:
      - RETRO_WEB_API_URL
      - RETRO_WEB_SOCKET_URL
    container_name: retro-web
    ports:
      - "80:8080"
    networks:
      - reverse-proxy_global
  retro-api:
    image: ghcr.io/newbies-workplace/retromachina-api:latest
    restart: unless-stopped
    container_name: retro-api
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - JWT_SECRET
      - DATABASE_URL
      - CALLBACK_URL
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - retro-back-local
      - reverse-proxy_global
    depends_on:
      - retro-db

networks:
  retro-back-local:
  reverse-proxy_global:
    external: true

volumes:
  retro-db:
