name: Code quality

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.8.1
      - name: Run Biome
        run: biome ci .
