name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: cd apps/web && npx playwright install --with-deps chromium
    - uses: getong/mariadb-action@v1.11
      with:
        host port: 3306
        container port: 3306
        mariadb version: '10.7'
        mysql database: 'retro'
        mysql root password: 'retro'
    - run: curl -sfS https://dotenvx.sh/install.sh | sh
    - name: Prepare test variables
      run: |
        echo "${{ secrets.DOTENV }}" > .env
        touch apps/web/playwright/.auth/first-user.json
        touch apps/web/playwright/.auth/second-user.json
        echo "${{ secrets.E2E_FIRST_AUTH }}" > apps/web/playwright/.auth/first-user.json
        echo "${{ secrets.E2E_SECOND_AUTH }}" > apps/web/playwright/.auth/second-user.json
    - name: Build the app
      run: npm run build
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: apps/web/playwright-report/
        retention-days: 7
