name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: apps/web/storybook-static
          build_command: cd apps/web && npm run build-storybook
